site_name: Boyd Bot (Messenger)
site_url: https://boyd-bot-messenger.readthedocs.io/en/latest/
site_author: Inesh Bose
site_description: >-
    Boyd Bot is an open-source university chatbot that helps
    students with their timetable. This is the documentation
    to help developers get started.

repo_url: https://github.com/ineshbose/boyd_bot_messenger
repo_name: boyd_bot_messenger

plugins:
    - search

theme:
    name: material
    language: en
    palette:
      primary: blue
      accent: cyan
    font:
      text: Roboto
    logo: images/bblogo.png
    favicon: images/favicon.ico

markdown_extensions:
    - codehilite


extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/ineshbose/boyd_bot_messenger
        - icon: fontawesome/brands/facebook
          link: https://facebook.com/uofgbot
        - icon: fontawesome/brands/facebook-messenger
          link: https://m.me/uofgbot
        - icon: fontawesome/brands/behance
          link: https://www.behance.net/gallery/93421281/Glasgow-University-Timetable-Bot

nav:
    - Home: index.md
    - Files:
      - __init__.py: files/init.md
      - bot.py: files/bot.md
      - timetable.py: files/timetable.md
      - views.py: files/views.md
      - forms.py: files/forms.md
      - services:
        - platform.py: files/services/platform.md
        - database.py: files/services/database.md
        - parser.py: files/services/parser.md
        - guard.py: files/services/guard.md
        - scheduler.py: files/services/scheduler.md
      - miscellaneous:
        - templates: files/miscellaneous/templates.md
        - _config.py: files/miscellaneous/config.md
        - run.py: files/miscellaneous/run.md
    - Services:
      - Facebook: services/facebook.md
      - mongoDB: services/mongodb.md
      - Dialogflow: services/dialogflow.md
      - Cryptography: services/cryptography.md
      - Wit: services/wit.md
      - Utilities: services/utilities.md
    - Others:
      - How It Works: others/working.md
      - Security: others/security.md